### ISSUE TITLE
pairsnp returned non-zero exit status 1

### ISSUE THREAD

**Issue by andersonbrito** [gtonkinhill/fasttranscluster#1]
Hi,

Thank you for developing `fasttranscluster`. Do you know what may be causing the issue below?

```
fasttranscluster --msa ./example_data/msa.fa --dates ./example_data/meta_data.csv -o run1
/bin/sh: run1/pairsnp_sparse_dist.csv: No such file or directory
Traceback (most recent call last):
  File "/anaconda3/bin/fasttranscluster", line 8, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/fasttranscluster/__main__.py", line 192, in main
    ncpu=args.n_cpu)
  File "/anaconda3/lib/python3.7/site-packages/fasttranscluster/pairsnp.py", line 15, in run_pairsnp
    subprocess.run(cmd, shell=True, check=True)
  File "/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'pairsnp -d 10 -t 1 -s ./example_data/msa.fa > run1/pairsnp_sparse_dist.csv' returned non-zero exit status 1.
```

Best,

**Comment by gtonkinhill** [comment]
Hi,

Does the 'run1' folder already exist? At the moment the program does not create the output folder itself.
This package is still in the early stages so its usability could be improved. I'm hoping to find time to work on it soon.

**Comment by andersonbrito** [comment]
Hey,

I've tried both creating the folder beforehand, and also without creating it.
In one of these attempts, I got an empty `pairsnp_sparse_dist.csv` file inside `run1`.

I wonder if this error is caused by the way how `pairsnp` is called by `fasttranscluster`:
> pairsnp -d 10 -t 1 -s ./example_data/msa.fa > run1/pairsnp_sparse_dist.csv

when I run `pairsnp -h`, I see the usage instruction below, which does not match the command syntax above:
> usage: pairsnp [-h] [-t {sim,dist}] [-n] -f FILENAME [-z] [-c] -o OUTPUT

**Comment by gtonkinhill** [comment]
Hmm, yes that looks like an older version of pairsnp. Hopefully installing the most recent version should help https://github.com/gtonkinhill/pairsnp-cpp

It should also speed things up a bit.
