### ISSUE TITLE
Pairsnp arguments have changed

### ISSUE THREAD

**Issue by darlancandido** [gtonkinhill/fasttranscluster#2]
Hi,

A colleague and I are trying to run fasttranscluster but an error related to argument -t keeps coming up. Apparently -t used to be the number of threads and it is set to 1. However, it is now the option for similarities or distances and only accepts sim or dist. Could you please check that?

Thank you
<img width="1653" alt="Screen Shot 2021-07-09 at 19 53 43" src="https://user-images.githubusercontent.com/64599126/125143165-25730580-e0f0-11eb-828a-37e33f251979.png">

**Comment by gtonkinhill** [comment]
Hi,

It looks like you might be using the python version of pairsnp. `fasttranscluster` uses the [c++](https://github.com/gtonkinhill/pairsnp-cpp) version 0.2.0. You can either install this manually or using [conda](https://anaconda.org/bioconda/pairsnp)

Please let me know if this doesn't resolve the issue.

**Comment by darlancandido** [comment]
Hi Gerry,


Thank you do much for the quick reply. You're right, I was trying the Python one. However, I am still having trouble installing it. Would you mind having a look at the error messages I am getting?


  1.  When trying with conda


UnsatisfiableError: The following specifications were found to be incompatible with each other:


Output in format: Requested package -> Available versions


Package libcxxabi conflicts for:

python=3.7 -> libcxx[version='>=4.0.1'] -> libcxxabi==4.0.1[build='hebd6815_0|hcfea43d_1']

pairsnp -> libcxx[version='>=4.0.1'] -> libcxxabi==4.0.1[build='hebd6815_0|hcfea43d_1']


Package libcxx conflicts for:

python=3.7 -> libffi[version='>=3.3,<3.4.0a0'] -> libcxx[version='>=10.0.0']

python=3.7 -> libcxx[version='>=4.0.1']


  1.  When doing it manually. It keeps asking me to install armadillo, which I have already installed a few times. So i don't really know why it is not finding it.

Apologies if this is a very simple thing to solve.

Thank you.

Darlan
________________________________

**Comment by gtonkinhill** [comment]
Hi,

I think I may have run into this issue before and it was something strange to do with the order of the channels specified to Conda. Can you try

```
conda install -c conda-forge -c bioconda pairsnp
```

If this works I will update the installation guide.

**Comment by darlancandido** [comment]
Dear Gerry,


Thank you very much. That did solve the issue with pairsnp. I now have been able to install it and to install fasttranscluster. However, when running on my dataset, it points to 233 cluster (1 for each sequence) regardless of -k. I am also getting error messages for iqtree2.

Would you know what the issue might be? Thank you so much for your willingness and patience.

Best wishes,

Darlan
________________________________

**Comment by gtonkinhill** [comment]
Hi Darlan,

The threshold will be a combination of the choice of `-K` and `-P` parameters. I usually use very liberal thresholds and then interrogate the pairwise relationships given in the resulting `transcluster_probabilities.csv` file separately using either python or R.

You may need to choose a lower `-P` initially as the default value of 0.8 is probably a bit high. The documentation is currently a bit lacking and I'm hoping to improve this soon.

If you could open a seperate issue with the problem you are encountering with Iqtree I'd be happy to take a look. I must admit we haven't used that option for a while so it may have broken with some of the more recent updates.
