### ISSUE TITLE
Incomplete example_data 

### ISSUE THREAD

**Issue by nairvarela** [gtonkinhill/fasttranscluster#3]
Dear Gerry, 

I am trying to run your program on my data but I am getting some errors. I wanted to try the program with the example_data on your GitHub but I can't find the file example_data/msa.fa to do a test run. Maybe I am missing one step to build this file ... Could you tell me how can I do a test run with the example_data to see whether I have installed the program correctly? 

Thank you a lot in advance. 

Best regards, 

Nair.

**Comment by gtonkinhill** [comment]
Hi Nair,

Sorry about that. I had updated the test/example data but failed to update the Readme. I have now updated it so please let me know if you run into any further issues.
